# Site settings
title: Foyzul Hassan
email: foyzul.hassan@my.utsa.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://foyzulhassan.github.io" # the base hostname & protocol for your site
github_username:  foyzulhassan
linkedin_username: foyzulhassan
googlescholar: https://scholar.google.com/citations?hl=en&user=b9Kw58UAAAAJ

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Graduate Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""

plugins:
  - jekyll-seo-tag
